/*
 * This file was automatically generated by EvoSuite
 * Wed May 10 17:55:03 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "E'dV+EKK", "E'dV+EKK");
      String string0 = appt0.toString();
      assertEquals("\t11/11/11 at 11:11am ,E'dV+EKK, E'dV+EKK\n", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(10, 10, 0, 10, 356, "", "");
      appt0.setStartDay(31);
      assertEquals(31, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(6, 59, 6, (-895), (-895), "Timezone", "N.Mh'TStAc&r2-4E~");
      assertEquals(6, appt0.getStartDay());
      assertEquals("Timezone", appt0.getTitle());
      assertEquals(-895, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(59, appt0.getStartMinute());
      assertEquals("N.Mh'TStAc&r2-4E~", appt0.getDescription());
      assertEquals(-895, appt0.getStartMonth());
      assertEquals(6, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt(2, 2, 2, 2, 2, (String) null, (String) null);
      boolean boolean0 = appt0.getValid();
      assertEquals(2, appt0.getStartDay());
      assertEquals(2, appt0.getStartHour());
      assertEquals(2, appt0.getStartMinute());
      assertTrue(boolean0);
      assertEquals(2, appt0.getStartYear());
      assertEquals(2, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "", "");
      appt0.getTitle();
      assertEquals(11, appt0.getStartHour());
      assertTrue(appt0.getValid());
      assertEquals(11, appt0.getStartYear());
      assertEquals(11, appt0.getStartDay());
      assertEquals(11, appt0.getStartMonth());
      assertEquals(11, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt((-1728), (-1728), (-1728), (-1728), 0, "\n", "\n");
      appt0.setStartYear(4091);
      int int0 = appt0.getStartYear();
      assertEquals(4091, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt(16, 23, (-876), (-876), (-876), (String) null, (String) null);
      int int0 = appt0.getStartYear();
      assertEquals(23, appt0.getStartMinute());
      assertEquals(-876, appt0.getStartDay());
      assertEquals(16, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals((-876), int0);
      assertEquals(-876, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt(46, 0, 0, 0, 46, "javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", "javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)");
      int int0 = appt0.getStartMonth();
      assertEquals("javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", appt0.getDescription());
      assertEquals(46, appt0.getStartYear());
      assertEquals(46, appt0.getStartHour());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartDay());
      assertEquals("javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", appt0.getTitle());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(10, 10, 0, 10, 356, "", "");
      assertEquals(10, appt0.getStartMinute());
      
      appt0.setStartMinute(0);
      int int0 = appt0.getStartMinute();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt((-362), (-362), (-362), (-362), (-362), "qQ^on*T9\"GRW#5YfB-^", "qQ^on*T9\"GRW#5YfB-^");
      int int0 = appt0.getStartMinute();
      assertEquals(-362, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(-362, appt0.getStartMonth());
      assertEquals("qQ^on*T9\"GRW#5YfB-^", appt0.getTitle());
      assertEquals("qQ^on*T9\"GRW#5YfB-^", appt0.getDescription());
      assertEquals(-362, appt0.getStartYear());
      assertEquals(-362, appt0.getStartDay());
      assertEquals((-362), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(284, 284, 284, 284, 284, "oqav", "oqav");
      int int0 = appt0.getStartHour();
      assertEquals("oqav", appt0.getTitle());
      assertEquals(284, appt0.getStartMonth());
      assertEquals(284, appt0.getStartMinute());
      assertEquals(284, appt0.getStartYear());
      assertEquals(284, appt0.getStartDay());
      assertEquals(284, int0);
      assertFalse(appt0.getValid());
      assertEquals("oqav", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(1090, 1228, 1090, 1090, 106, (String) null, (String) null);
      appt0.setStartHour((-548));
      int int0 = appt0.getStartHour();
      assertEquals((-548), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt(46, 0, 0, 0, 46, "javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", "javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)");
      int int0 = appt0.getStartDay();
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, int0);
      assertFalse(appt0.getValid());
      assertEquals("javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", appt0.getTitle());
      assertEquals("javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", appt0.getDescription());
      assertEquals(46, appt0.getStartHour());
      assertEquals(46, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt((-1649), 10, 60, (-3158), 60, "/", "/");
      int int0 = appt0.getStartDay();
      assertEquals("/", appt0.getTitle());
      assertEquals(60, int0);
      assertEquals(-1649, appt0.getStartHour());
      assertEquals("/", appt0.getDescription());
      assertEquals(60, appt0.getStartYear());
      assertEquals(10, appt0.getStartMinute());
      assertEquals(-3158, appt0.getStartMonth());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt((-1316), (-1316), (-1316), (-1316), (-1316), (String) null, (String) null);
      String string0 = appt0.getDescription();
      assertEquals(-1316, appt0.getStartHour());
      assertEquals(-1316, appt0.getStartYear());
      assertNotNull(string0);
      assertEquals(-1316, appt0.getStartDay());
      assertEquals(-1316, appt0.getStartMinute());
      assertEquals(-1316, appt0.getStartMonth());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt((-1530), (-1530), (-1530), 2000, 2000, "CgcGdILio", "CgcGdILio");
      appt0.setDescription("UnknownField");
      assertEquals("UnknownField", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt((-362), (-362), (-362), (-362), (-362), "qQ^on*T9\"GRW#5YfB-^", "qQ^on*T9\"GRW#5YfB-^");
      assertEquals("qQ^on*T9\"GRW#5YfB-^", appt0.getDescription());
      
      appt0.setDescription((String) null);
      assertEquals(-362, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt((-4087), (-4087), (-4087), 0, 0, "]}m@+", "E\"P6*^\"dl; hhY'");
      assertEquals("]}m@+", appt0.getTitle());
      
      appt0.setTitle("");
      assertEquals(-4087, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 2245, "", "");
      appt0.setTitle((String) null);
      assertEquals(2245, appt0.getStartYear());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt((-1728), (-1728), (-1728), (-1728), 0, "\n", "\n");
      String string0 = appt0.getTitle();
      assertEquals(-1728, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(-1728, appt0.getStartMonth());
      assertEquals(-1728, appt0.getStartMinute());
      assertEquals("\n", string0);
      assertEquals("\n", appt0.getDescription());
      assertEquals(0, appt0.getStartYear());
      assertEquals(-1728, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt((-1530), (-1530), (-1530), 2000, 2000, "CgcGdILio", "CgcGdILio");
      int int0 = appt0.getStartDay();
      assertEquals(2000, appt0.getStartYear());
      assertEquals((-1530), int0);
      assertEquals(-1530, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals("CgcGdILio", appt0.getTitle());
      assertEquals(2000, appt0.getStartMonth());
      assertEquals(-1530, appt0.getStartMinute());
      assertEquals("CgcGdILio", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt((-670), 7, 3879, (-670), (-670), "ARcq$i_", ", ");
      boolean boolean0 = appt0.getValid();
      assertEquals(-670, appt0.getStartMonth());
      assertEquals(", ", appt0.getDescription());
      assertEquals(3879, appt0.getStartDay());
      assertFalse(boolean0);
      assertEquals(7, appt0.getStartMinute());
      assertEquals(-670, appt0.getStartHour());
      assertEquals("ARcq$i_", appt0.getTitle());
      assertEquals(-670, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "aWK", "QN/4_%");
      int int0 = appt0.getStartHour();
      assertEquals("aWK", appt0.getTitle());
      assertEquals("QN/4_%", appt0.getDescription());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt((-1728), (-1728), (-1728), (-1728), 0, "\n", "\n");
      int int0 = appt0.getStartYear();
      assertEquals(-1728, appt0.getStartHour());
      assertEquals("\n", appt0.getTitle());
      assertEquals(0, int0);
      assertEquals(-1728, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals("\n", appt0.getDescription());
      assertEquals(-1728, appt0.getStartMinute());
      assertEquals(-1728, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(10, 10, 0, 10, 356, "", "");
      int int0 = appt0.getStartMinute();
      assertEquals(10, appt0.getStartHour());
      assertEquals(356, appt0.getStartYear());
      assertEquals(0, appt0.getStartDay());
      assertEquals(10, int0);
      assertFalse(appt0.getValid());
      assertEquals(10, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt((-1530), (-1530), (-1530), 2000, 2000, "CgcGdILio", "CgcGdILio");
      String string0 = appt0.getDescription();
      assertEquals("CgcGdILio", appt0.getTitle());
      assertEquals(2000, appt0.getStartYear());
      assertEquals(-1530, appt0.getStartMinute());
      assertEquals(-1530, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(-1530, appt0.getStartHour());
      assertEquals(2000, appt0.getStartMonth());
      assertEquals("CgcGdILio", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt(10, 10, 0, 10, 356, "", "");
      int int0 = appt0.getStartMonth();
      assertEquals(10, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(356, appt0.getStartYear());
      assertEquals(10, int0);
      assertEquals(10, appt0.getStartHour());
      assertEquals(0, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "((", "((");
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t12/12/12 at 12:12pm ,((, ((\n", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "aWK", "QN/4_%");
      String string0 = appt0.toString();
      assertEquals(0, appt0.getStartYear());
      assertEquals("QN/4_%", appt0.getDescription());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, appt0.getStartMonth());
      assertNull(string0);
      assertEquals(0, appt0.getStartMinute());
      assertEquals("aWK", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt(13, 13, 13, 13, 13, "", (String) null);
      assertFalse(appt0.getValid());
      assertEquals(13, appt0.getStartDay());
      assertEquals(13, appt0.getStartMonth());
      assertEquals(13, appt0.getStartMinute());
      assertEquals(13, appt0.getStartYear());
      assertEquals(13, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(10, 10, 0, 10, 356, "", "");
      assertEquals(0, appt0.getStartDay());
      
      appt0.setStartDay(356);
      assertEquals(356, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(0, (-2403), (-2403), (-2403), 3134, "", "");
      int int0 = appt0.getStartMonth();
      assertEquals(3134, appt0.getStartYear());
      assertEquals(0, appt0.getStartHour());
      assertEquals(-2403, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals((-2403), int0);
      assertEquals(-2403, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Appt appt0 = new Appt(2562, 2562, 2562, 23, 492, "", "");
      assertEquals(2562, appt0.getStartHour());
      
      appt0.setStartHour(23);
      assertEquals(23, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "E'dV+EKK", "E'dV+EKK");
      appt0.setStartMonth((-2));
      assertEquals(-2, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Appt appt0 = new Appt(2, 2, 2, 2, 2, "", "");
      String string0 = appt0.toString();
      assertEquals("\t2/2/2 at 2:2am ,, \n", string0);
      assertNotNull(string0);
  }
}
