/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 21 04:25:22 GMT 2017
 */

package container;

import org.junit.Test;
import static org.junit.Assert.*;
import container.Container;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Container_ESTest extends Container_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      Container container0 = new Container();
      container0.put((-996));
      int int0 = container0.size();
      assertEquals(1, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      Container container0 = new Container();
      int int0 = container0.size();
      assertEquals(0, int0);
  }

  @Test
  public void test2()  throws Throwable  {
      Container container0 = new Container();
      container0.put(0);
      assertEquals(1, container0.size());
      
      int int0 = container0.remove(0);
      assertEquals(1, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      Container container0 = new Container();
      int int0 = container0.remove(1);
      assertEquals(0, int0);
  }

  @Test
  public void test4()  throws Throwable  {
      Container container0 = new Container();
      container0.put(0);
      int int0 = container0.put(0);
      assertEquals(1, container0.size());
      assertEquals(0, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      Container container0 = new Container();
      container0.put(0);
      container0.printContainer();
      assertEquals(1, container0.size());
  }

  @Test
  public void test6()  throws Throwable  {
      Container container0 = new Container();
      container0.put(0);
      int int0 = container0.get(0);
      assertEquals(1, container0.size());
      assertEquals(1, int0);
  }

  @Test
  public void test7()  throws Throwable  {
      Container container0 = new Container();
      int int0 = container0.get(0);
      assertEquals(0, int0);
  }
}
